require "globals"
require "plugins.packer"
require "plugins.telescope"
require "plugins.orgmode"
require "plugins.lsp"
require "plugins.nvim-cmp"
require "plugins.neogit"
require "plugins.diffview"
require "plugins.mini"

